- name: Run Scraper
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        SESSION_STRING: ${{ secrets.SESSION_STRING }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      run: python scraper.py
