- name: Run Scraper
      env:
        # Make sure these names MATCH exactly what is in your Secrets
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        SESSION_STRING: ${{ secrets.SESSION_STRING }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      run: python scraper.py
